import 'dart:convert' show json;
import 'dart:developer' show log;
import 'dart:io' show File, Directory;

import 'package:alheekmahlib_website/core/utils/constants/extensions/convert_number_extension.dart';
import 'package:alheekmahlib_website/core/utils/constants/extensions/dimensions.dart';
import 'package:alheekmahlib_website/core/utils/constants/extensions/text_span_extension.dart';
import 'package:animated_custom_dropdown/custom_dropdown.dart';
import 'package:animated_search_bar/animated_search_bar.dart';
import 'package:dio/dio.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:gap/gap.dart';
import 'package:get/get.dart';
import 'package:get_storage/get_storage.dart';
import 'package:go_router/go_router.dart';

import '/core/utils/constants/extensions/custom_error_snack_bar.dart';
import '/core/utils/constants/extensions/extensions.dart';
import '/core/utils/constants/extensions/svg_extensions.dart';
import '../../../core/utils/constants/lottie.dart';
import '../../../core/utils/constants/shared_preferences_constants.dart';
import '../../core/services/services_locator.dart';
import '../../core/utils/constants/svg_constants.dart';
import '../../core/utils/helpers/app_router.dart';
import '../../core/utils/helpers/url_helper.dart';
import '../../core/widgets/custom_button.dart';
import '../../core/widgets/font_size_drop_down.dart';
import '../../core/widgets/read_more_less/read_more_less.dart';
import '../../core/widgets/search_bar_widget.dart';
import '../../core/widgets/settings_title_widget.dart';
import '../../core/widgets/shimmer_effect_build.dart';
import '../controllers/general_controller.dart';
import '../controllers/theme_controller.dart';
import 'controller/chapters_controller.dart';

part 'controller/books_controller.dart';
part 'controller/books_state.dart';
part 'controller/extensions/books_getters.dart';
part 'controller/extensions/books_storage_getters.dart';
part 'controller/extensions/books_ui.dart';
part 'data/models/book_info_model.dart';
part 'data/models/books_model.dart';
part 'data/models/chapter_model.dart';
part 'data/models/page_model.dart';
part 'data/models/part_model.dart';
part 'data/models/toc_model.dart';
part 'data/models/volume_model.dart';
part 'data/services/books_data_converter.dart';
part 'screens/books_screen.dart';
part 'screens/chapters_screen.dart';
part 'screens/read_view_screen.dart';
part 'widgets/all_books_build.dart';
part 'widgets/book_cover_widget.dart';
part 'widgets/book_details_widget.dart';
part 'widgets/books_bottom_options_widget.dart';
part 'widgets/books_chapters_build.dart';
part 'widgets/books_last_read.dart';
part 'widgets/books_tab_bar_widget.dart';
part 'widgets/change_theme_widget.dart';
part 'widgets/chapters_dropdown_widget.dart';
part 'widgets/chapters_list_widget.dart';
part 'widgets/search_bottom_sheet.dart';
part 'widgets/search_build.dart';
part 'widgets/search_screen.dart';
